// Generated by Wrangler by running `wrangler types`

interface Env {
	DELETE_POST_MAP: KVNamespace;
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	OPENAI_API_KEY: string;
	COMPRESS_IMAGE: any;
}
