#:schema node_modules/wrangler/config-schema.json
name = "kuromichan"
main = "src/server.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-10-11"

[[services]]
binding = "COMPRESS_IMAGE"
service = "image-compresser"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "DELETE_POST_MAP"
id = "8129129da38e414aa933fbba3eb5ce13"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# OPENAI_API_KEY