name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      # install wrangler
      - name: Install wrangler
        run: npm install -g wrangler

      # Discord Token を Cloudflare Workers に追加
      - name: Set Discord Token as secret
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: wrangler secret put DISCORD_TOKEN --from-env DISCORD_TOKEN

      # Discord Public Key を Cloudflare Workers に追加
      - name: Set Discord Public Key as secret
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
        run: wrangler secret put DISCORD_PUBLIC_KEY --from-env DISCORD_PUBLIC_KEY

      # Discord Application ID を Cloudflare Workers に追加
      - name: Set Discord Application ID as secret
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        run: wrangler secret put DISCORD_APPLICATION_ID --from-env DISCORD_APPLICATION_ID

      # TypeScript をビルドして dist フォルダに出力
      - name: Build TypeScript files
        run: npm install && npm run build

      # Discord コマンドを登録
      - name: Register Discord commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        run: npm run register

      # Cloudflare Workers へのデプロイ
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
